### ISSUE TITLE
投稿関係

### ISSUE THREAD

**Issue by hkoukan** [kassyinkyoto11/travel_watnow#4]
## ユーザとのリレーション
- [x] ユーザと関連付いた投稿を行えるようにする
- [x] リレーションを設定し、投稿詳細で投稿ユーザ名を表示＆ユーザ詳細で投稿一覧を見れるようにする

## その他
- [x] シードデータを投入して動作確認を行う
- [x] ページネーションのデフォルト値を直す
- [x] season,wayをenumで定義し直す & フォーム部分もそれに伴って修正

**Comment by hkoukan** [comment]
> ## ログインしている人じゃないと見れないようにする
> ## 誰が投稿したかわかるようにする
>## 投稿者だけが削除、編集できるようにする

**Comment by kassyinkyoto11** [comment]
wayの投稿がnilになってしまう問題が発生中
